# Generated by Django 6.0.1 on 2026-01-26 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_complet', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=15)),
                ('specializare', models.CharField(choices=[('cardio', 'Cardiologie'), ('derma', 'Dermatologie'), ('pneumo', 'Pneumologie')], max_length=20)),
                ('data_programare', models.DateField()),
                ('mesaj', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
