# Generated by Django 6.0.1 on 2026-04-11 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('specializare', models.CharField(choices=[('cardio', 'Cardiologie'), ('derma', 'Dermatologie'), ('pneumo', 'Pneumologie')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='programare',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.doctor'),
        ),
    ]
