# Generated by Django 6.0.1 on 2026-04-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_doctor_programare_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specializare',
            field=models.CharField(choices=[('cardiologie', 'Cardiologie'), ('dermatologie', 'Dermatologie'), ('pneumologie', 'Pneumologie')], max_length=20),
        ),
        migrations.AlterField(
            model_name='programare',
            name='specializare',
            field=models.CharField(choices=[('cardiologie', 'Cardiologie'), ('dermatologie', 'Dermatologie'), ('pneumologie', 'Pneumologie')], max_length=20),
        ),
    ]
