# Generated by Django 6.0.1 on 2026-04-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_alter_doctor_specializare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='nume_poza',
            field=models.CharField(default='default.jpg', max_length=100),
        ),
    ]
