# Generated by Django 6.0.1 on 2026-04-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_doctor_nume_poza'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='descriere',
            field=models.TextField(blank=True, null=True),
        ),
    ]
